image: docker:latest
services:
  - docker:dind

stages:
  - build
  - package
  - deploy

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

maven-build:
  image: maven:3-openjdk-11
  stage: build
  script:
    - mvn package -B
  artifacts:
    paths:
      - target/*.jar
