version: "3"

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge
    restart: always
    ports:
      - 1433:1433
    volumes:
      - ~/Volumes/sqledge:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    cap_add:
      - SYS_PTRACE
    networks:
      - backend
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - backend
  app-server:
    image: issue-tracker
    depends_on:
      - db
      - redis
    restart: always
    expose:
      - 8080
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASS: ${REDIS_PASS}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - frontend
      - backend
  gateway:
    image: nginx
    depends_on:
      - app-server
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontend

networks:
  frontend:
  backend:
