INSERT INTO app_user (name) VALUES ('Peter');
INSERT INTO app_user (name) VALUES ('Paul');
INSERT INTO app_user (name) VALUES ('Mary');
INSERT INTO issue_type (name, icon) VALUES ('New Feature', 'bi-file-earmark-medical');
INSERT INTO issue_type (name, icon) VALUES ('Enhancement', 'bi-file-earmark-plus');
INSERT INTO issue_type (name, icon) VALUES ('Task', 'bi-clipboard-check');
INSERT INTO issue_type (name, icon) VALUES ('Bug', 'bi-bug');
INSERT INTO issue_type (name, icon) VALUES ('Incident', 'bi-exclamation-triangle');
INSERT INTO issue_status (name) VALUES ('Backlog');
INSERT INTO issue_status (name) VALUES ('Todo');
INSERT INTO issue_status (name) VALUES ('In Progress');
INSERT INTO issue_status (name) VALUES ('Done');
