apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
type: Opaque
data:
  mssql.sa.password: WnNlNDRyZnY=
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  redis.password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db.user: aXRfZGV2
  db.password: aXRfZGV2MTIz
